# Generated by Django 5.1.3 on 2024-11-20 13:40

from django.db import migrations
from django.contrib.auth.hashers import make_password

def add_initial_users(apps, schema_editor):
    CustomUser = apps.get_model('account', 'CustomUser')

    new_users = [
        ('admin@example.com', 'admin', True),
        ('client1@example.com', 'client1', False),
        ('client2@example.com', 'client2', False),
        ('client3@example.com', 'client3', False)
    ]

    for email, password, is_superuser in new_users:
        if not CustomUser.objects.filter(email=email).exists():
            user = CustomUser(
                email=email,
                is_superuser=is_superuser,
                is_staff=is_superuser,
                password=make_password(password)
            )
            user.save()
   

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_users),
    ]