# Generated by Django 5.1.3 on 2024-11-19 14:30

from django.db import migrations

def add_initial_categories(apps, schema_editor):
    # Add initial product/images to the database
    Category = apps.get_model('product', 'Category')
    Department = apps.get_model('product', 'Department')

    # Departamento, secciones del departamento:
    new_departments_sections = {
        'Cocina': ['Electrodomesticos', 'Utensilios de Cocina', 'Pequeños Electrodomésticos', 'Almacenamiento de Alimentos', 'Otros'],
        'Electrónica': ['Audio y Sonido', 'Televisores y Video'],
        'Hogar': ['Muebles', 'Decoración'],
        'Jardinería': ['Herramientas de Jardín'],
        'Deportes': ['Fitness', 'Outdoor'],
        'Oficina': ['Equipos de Oficina', 'Suministros'],
        'Salud': ['Equipos Médicos']
    }

    # Iterar sobre los departamentos y secciones para crear las categorías
    for name_department, categories in new_departments_sections.items():
        department = Department.objects.create(name=name_department)
        for category in categories:
            Category.objects.create(name=category, department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories)
    ]
