# Generated by Django 5.1.3 on 2024-11-19 14:30

from django.db import migrations

def add_initial_products(apps, schema_editor):
    # Add initial product/images to the database
    Product = apps.get_model('product', 'Product')
    Department = apps.get_model('product', 'Department')
    Category = apps.get_model('product', 'Category')

    # Obtener los departamentos
    cocina = Department.objects.get(name='Cocina')

    # Obtener las categorías
    electrodomesticos = Category.objects.get(department=cocina, name='Electrodomesticos')
    utensilios = Category.objects.get(department=cocina, name='Utensilios de Cocina')
    peque_electro = Category.objects.get(department=cocina, name='Pequeños Electrodomésticos')
    almacenamiento = Category.objects.get(department=cocina, name='Almacenamiento de Alimentos')
    otros = Category.objects.get(department=cocina, name='Otros')

    Product.objects.create(
        name='Refrigerador Samsung Family Hub',
        description='Refrigerador inteligente con pantalla táctil y conectividad Wi-Fi.',
        price=2499.99,
        image='product/images/refrigerador_samsung_family_hub.jpg',
        maker='Samsung',
        stock=30,
        category=electrodomesticos
    )
    
    Product.objects.create(
        name='Lavavajillas Bosch Serie 6',
        description='Lavavajillas eficiente con múltiples programas de lavado.',
        price=899.99,
        image='product/images/lavavajillas_bosch_serie6.jpg',
        maker='Bosch',
        stock=20,
        category=electrodomesticos
    )
    
    Product.objects.create(
        name='Horno Microondas LG NeoChef',
        description='Microondas con tecnología inverter para cocción uniforme.',
        price=299.99,
        image='product/images/microondas_lg_neochef.jpg',
        maker='LG',
        stock=0,
        category=electrodomesticos
    )
    
    Product.objects.create(
        name='Placa de Inducción Teka IIC',
        description='Placa de inducción de 4 zonas con controles táctiles.',
        price=499.99,
        image='product/images/placa_induccion_teka_iic.jpg',
        maker='Teka',
        stock=25,
        category=electrodomesticos
    )
    
    Product.objects.create(
        name='Extractor de Aire Siemens iQ700',
        description='Extractor de aire silencioso con sensor de humedad.',
        price=399.99,
        image='product/images/extractor_aire_siemens_iq700.jpg',
        maker='Siemens',
        stock=15,
        category=electrodomesticos
    )
    
    # Sección: Utensilios de Cocina
    Product.objects.create(
        name='Juego de Cuchillos Global 8 Piezas',
        description='Set de cuchillos japoneses de alta calidad para cocina profesional.',
        price=149.99,
        image='product/images/cuchillos_global_8piezas.jpg',
        maker='Global',
        stock=100,
        category=utensilios
    )
    
    Product.objects.create(
        name='Sartenes Tefal Titanium',
        description='Juego de sartenes antiadherentes con tecnología Titanium.',
        price=129.99,
        image='product/images/sartenes_tefal_titanium.jpg',
        maker='Tefal',
        stock=80,
        category=utensilios
    )
    
    Product.objects.create(
        name='Set de Ollas Le Creuset',
        description='Juego de ollas de hierro fundido esmaltado de alta calidad.',
        price=599.99,
        image='product/images/ollas_lecreuset.jpg',
        maker='Le Creuset',
        stock=0,
        category=utensilios
    )
    
    Product.objects.create(
        name='Batidora KitchenAid Artisan',
        description='Batidora de pie con múltiples accesorios y colores disponibles.',
        price=349.99,
        image='product/images/batidora_kitchenaid_artisan.jpg',
        maker='KitchenAid',
        stock=60,
        category=utensilios
    )
    
    Product.objects.create(
        name='Tabla de Cortar de Bambú',
        description='Tabla de cortar ecológica y resistente para todo tipo de alimentos.',
        price=29.99,
        image='product/images/tabla_cortar_bambu.jpg',
        maker='OXO',
        stock=150,
        category=utensilios
    )
    
    # Sección: Pequeños Electrodomésticos
    Product.objects.create(
        name='Tostadora Philips Daily Collection',
        description='Tostadora con 6 niveles de tostado y funciones de descongelado.',
        price=49.99,
        image='product/images/tostadora_philips_daily.jpg',
        maker='Philips',
        stock=70,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Cafetera Nespresso Vertuo',
        description='Cafetera cápsulas con tecnología de centrifusión para café y espresso.',
        price=199.99,
        image='product/images/cafetera_nespresso_vertuo.jpg',
        maker='Nespresso',
        stock=55,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Licuadora Vitamix 5200',
        description='Licuadora de alto rendimiento para smoothies y batidos.',
        price=449.99,
        image='product/images/licuadora_vitamix_5200.jpg',
        maker='Vitamix',
        stock=35,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Freidora de Aire Philips',
        description='Freidora de aire saludable con tecnología Rapid Air.',
        price=299.99,
        image='product/images/freidora_aire_philips.jpg',
        maker='Philips',
        stock=45,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Robot de Cocina Moulinex Companion',
        description='Robot multifunción para picar, cocinar y amasar.',
        price=599.99,
        image='product/images/robot_cocina_moulinex_companion.jpg',
        maker='Moulinex',
        stock=25,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Cafetera Espresso DeLonghi Magnifica',
        description='Máquina de café espresso automática con molinillo integrado.',
        price=699.99,
        image='product/images/cafetera_delonghi_magnifica.jpg',
        maker='DeLonghi',
        stock=20,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Plancha para Panini Breville',
        description='Plancha eléctrica para paninis y sándwiches con placas antiadherentes.',
        price=89.99,
        image='product/images/plancha_panini_breville.jpg',
        maker='Breville',
        stock=65,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Extractor de Jugos Omega J8006',
        description='Extractor de jugos de alta eficiencia para jugos fríos.',
        price=349.99,
        image='product/images/extractor_jugos_omega_j8006.jpg',
        maker='Omega',
        stock=30,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Máquina de Hacer Pan Panasonic SD-YD250',
        description='Máquina automática para hacer pan con múltiples programas.',
        price=199.99,
        image='product/images/maquina_pan_panasonic_sdyd250.jpg',
        maker='Panasonic',
        stock=40,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Humidificador Philips Series 2000',
        description='Humidificador ultrasónico con control de humedad y apagado automático.',
        price=129.99,
        image='product/images/humidificador_philips_series2000.jpg',
        maker='Philips',
        stock=50,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Ventilador de Escritorio Honeywell HT-900E',
        description='Ventilador compacto y silencioso para uso en cocina.',
        price=39.99,
        image='product/images/ventilador_honeywell_ht900e.jpg',
        maker='Honeywell',
        stock=100,
        category=peque_electro
    )
    
    Product.objects.create(
        name='Calentador de Agua Instantáneo Ariston',
        description='Calentador de agua sin depósito con rápida provisión de agua caliente.',
        price=299.99,
        image='product/images/calentador_agua_ariston.jpg',
        maker='Ariston',
        stock=20,
        category=peque_electro
    )
    
    # Sección: Almacenamiento de Alimentos
    Product.objects.create(
        name='Despensa Inteligente SmartStor',
        description='Sistema de almacenamiento modular con sensores de temperatura.',
        price=499.99,
        image='product/images/despensa_inteligente_smartstor.jpg',
        maker='SmartStor',
        stock=10,
        category=almacenamiento
    )
    
    Product.objects.create(
        name='Contenedores Herméticos Lock&Lock',
        description='Juego de 20 contenedores plásticos con cierre hermético.',
        price=59.99,
        image='product/images/contenedores_locklock.jpg',
        maker='Lock&Lock',
        stock=200,
        category=almacenamiento
    )
    
    Product.objects.create(
        name='Envasadora al Vacío FoodSaver V4840',
        description='Máquina de envasado al vacío con múltiples modos de sellado.',
        price=199.99,
        image='product/images/envasadora_foodsaver_v4840.jpg',
        maker='FoodSaver',
        stock=35,
        category=almacenamiento
    )
    
    Product.objects.create(
        name='Refrigerador de Vino Vinotemp 24 Botellas',
        description='Refrigerador especializado para almacenamiento de vinos con control de temperatura.',
        price=799.99,
        image='product/images/refrigerador_vinotemp_24botellas.jpg',
        maker='Vinotemp',
        stock=15,
        category=almacenamiento
    )
    
    # Sección: Otros
    Product.objects.create(
        name='Máquina de Hacer Café Moka',
        description='Máquina de café tradicional italiana para preparar moka pot.',
        price=49.99,
        image='product/images/maquina_cafe_moka.jpg',
        maker='Bialetti',
        stock=80,
        category=otros
    )
    
    Product.objects.create(
        name='Set de Medidores de Cocina OXO',
        description='Juego de medidores de cocina en acero inoxidable con imán.',
        price=39.99,
        image='product/images/medidores_oxo.jpg',
        maker='OXO',
        stock=120,
        category=otros
    )

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_add_data_categories'),
    ]

    operations = [
        migrations.RunPython(add_initial_products)
    ]
