# Generated by Django 5.1.3 on 2024-11-18 18:49

import django.core.validators
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=125)),
                ('total', models.DecimalField(decimal_places=2, help_text='El total debe ser un valor positivo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('address', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('paymentMethod', models.CharField(choices=[('OD', 'On Delivery'), ('CC', 'Credit Card')], default='OD', max_length=2)),
                ('deliveryDate', models.DateTimeField(validators=[order.models.validate_delivery_date])),
            ],
        ),
    ]
