# Generated by Django 5.1.3 on 2024-11-20 14:51

import django.core.validators
import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_update_icons_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=125)),
                ('total', models.DecimalField(decimal_places=2, help_text='El total debe ser un valor positivo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('address', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('paymentMethod', models.CharField(choices=[('OD', 'On Delivery'), ('CC', 'Credit Card')], default='OD', max_length=2)),
                ('deliveryDate', models.DateField(validators=[order.models.validate_delivery_date])),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='La cantidad debe ser al menos 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='product.product')),
            ],
        ),
    ]
